### ISSUE TITLE
Possible Infinite loop

### ISSUE THREAD

**Issue by scuniff** [ome/ome-poi#13]
https://github.com/ome/ome-poi/blob/ba0d5d20f06786801c40d77e9b91346d485a17c8/src/main/java/loci/poi/hssf/usermodel/EscherGraphics2d.java#L334

It appears to be an infinite loop at line 334:

    public void drawString(AttributedCharacterIterator attributedcharacteriterator, int x, int y)
    {
        drawString(attributedcharacteriterator, x, y);
    }

Was the overloaded method at line 323 meant to be called?

` public void drawString(AttributedCharacterIterator attributedcharacteriterator, float x, float y)`

So change line 334 to this?:

    drawString(attributedcharacteriterator,(float) x, (float) y);

**Comment by joshmoore** [comment]
:+1:

**Comment by dgault** [comment]
Thanks @scuniff for spotting this and raising the issue. I have opened an initial PR for this Issue, but that may lead to further work to try to realign this project with the upstream.
